name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  NODE_ENV: test

jobs:
  build:
    timeout-minutes: 8
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm run build --if-present
      - run: npx jest --coverage

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONARCLOUD_TOKEN }}
        with:
          # Additional arguments for the sonarcloud scanner
          args:
            # Unique keys of your project and organization. You can find them in SonarCloud > Information (bottom-left menu)
            -Dsonar.projectKey=kinstella_cloverbadge-action
            -Dsonar.organization=kinstella
            -Dsonar.exclusions=*__tests__**/*.js
            -Dsonar.language=js
            -Dsonar.sourceEncoding=UTF-8
            -Dsonar.sources=.
            -Dsonar.javascript.lcov.reportPaths=./testCoverage/lcov.info